waggle-sensor/edge-scheduler

- .github/workflows/release.yaml
- build.sh
- cmd/runplugin/main.go
- pkg/runplugin/runplugin.go
As part of [Sage-817], I wanted to start using the SES runplugin command Yongho and I worked on to deploy plugins.
To encourage that transition, I set up an action which automatically creates a release with the multi-arch go build executables as assets. All you have to do is tag a commit with `v*.*.*`.
> Setup automated "go build" Github Action.

- pkg/runplugin/runplugin.go
Data sharing service expected plugins' RabbitMQ username to follow a `plugin.name:version` format. I've updated this.
See the wes-data-sharing-service for implementation details: https://github.com/waggle-sensor/wes-data-sharing-service/blob/main/main.py#L34
> [SAGE-817] Fixed plugin username

- cmd/runplugin/main.go
I improved support for env vars so admin's can simply do things like:
```sh
export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
export RABBITMQ_MANAGEMENT_URI="http://$(kubectl get svc wes-rabbitmq -o jsonpath='{.spec.clusterIP}'):15672"
export RABBITMQ_MANAGEMENT_USERNAME=admin
export RABBITMQ_MANAGEMENT_PASSWORD=admin
./runplugin-arm64 waggle/plugin-image-sampler:0.1.0 -stream bottom_image
./runplugin-arm64 waggle/plugin-audio-sampler:0.1.1
./runplugin-arm64 waggle/plugin-test-pipeline:0.0.3
```
> Improve runplugin tool user experience

- pkg/runplugin/runplugin.go
I realized the pulseaudio server address was hard coded by default in the audio sampler. This adds it to any plugin deployed with runplugin, so, we can finally have other audio plugins. 🎶
> SAGE-1002 added PULSE_SERVER envvar to runplugin template

- pkg/runplugin/runplugin.go
This addition will provide plugins to access to the Pod UID they are running in. This will allow us to tag measurements with metadata such as where a Pod was scheduled.
> [SAGE-1007] Provide plugin access to Pod UID using downward API.

- cmd/runplugin/args.go
- cmd/runplugin/args_test.go
- cmd/runplugin/main.go
- pkg/runplugin/runplugin.go
- pkg/runplugin/runplugin_test.go
This adds support for the --selector flag to runplugin which allows you to constrain where a plugin runs based on labels instead of just node like we had before.
For example:
```sh
runplugin --selector resource.gps=true waggle/plugin-test-pipeline:0.2.8
```
Multiple labels can be provided as a comma separated list --selector l1=v1,l2=v2,....
> Added support for label selector.

- pkg/nodescheduler/resourcemanager.go
The ttlseconds was set to 1 minute, which was too short. This possibly made the `wes-data-sharing-service` crashed, and also made the queue piling up messages.
```
to-validator | classic | D | running | 237,024 | 134,910 | 371,934 | 3.0/s | 775/s | 0.20/s
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[to-validator](http://localhost:15672/#/queues/%2F/to-validator)
classic	D	running	237,024	134,910	371,934	3.0/s	775/s	0.20/s
```
```bash
2022/02/28 16:06:18 invalid message: no pod with uid 'e4ff06c2-bd53-4e3f-b6c6-f8940b466480'
Traceback (most recent call last):
File "main.py", line 53, in load_message
pod = appstate.pods[properties.app_id]
KeyError: 'e4ff06c2-bd53-4e3f-b6c6-f8940b466480'
During handling of the above exception, another exception occurred:
Traceback (most recent call …
```
> A quick fix on setting the right ttlseconds for the garbage collector

- pkg/nodescheduler/resourcemanager.go
- pkg/runplugin/runplugin.go
This will allow the upload pipeline to provide the job to the OSN uploader so that upload URLs will be correct.
> Added job to upload path.

- pkg/nodescheduler/resourcemanager.go
When the following error occurred, the node scheduler didn't handle it properly, resulting in leaving the plugin status Running forever (and it was not running due to the error). To properly handle this kind of error, we treat it as "plugin status failure" instead of general failure. This way, the scheduler will attempt to schedule it whenever needed.
```bash
ERROR: 2022/05/18 04:01:00 resourcemanager.go:844: Failed to run "sound-event-detection-1652846450": "Post \"https://10.43.0.1:443/apis/batch/v1/namespaces/ses/jobs\": context deadline exceeded"
```
> Fixed a bug on handling k3s failure for running plugin

- cmd/cloudscheduler/main.go
- pkg/cloudscheduler/api_server.go
- pkg/cloudscheduler/builder.go
- pkg/cloudscheduler/cloudgoalmanager.go
- pkg/cloudscheduler/cloudscheduler.go
- pkg/cloudscheduler/validator.go
- pkg/datatype/event.go
- pkg/datatype/sciencegoal.go
- `--no-push-notification` disables the push notification through `api/v1/goals/{NODE}/stream`. By default, cloud scheduler uses the endpoint for nodes as a client to get goal updates as jobs being submitted and updated by users.
> Cloud scheduler pushes goals to clients in the SSE stream

- cmd/pluginctl/cmd/build.go
This PR adds a pluginctl build command which allows building to a local registry.
I'm opening the PR early as it implements the minimal functionality needed for the dev workflow. Some open questions are still:
* Do we want multiple arch builds? (NX and RPi share arch and OS, so may not be needed immediately.)
* Do we want any other flags? (Right now, you can specify an explicit tag with -t. Should we extended this? Remove it?)
* Use sage.yaml?
> SAGE-1437: Add pluginctl build command

- pkg/nodescheduler/resourcemanager.go
This PR adds a priority class which matches the priority class here: https://github.com/waggle-sensor/waggle-edge-stack/blob/e28e383b5fdffe06554471faadf7cfcf3cb0f560/kubernetes/wes-priority-classes.yaml#L9
This simply opts-in apps to start using this policy. The policy itself is independently defined and updated in WES.
> Sage-1471: Added priority class to pod spec.

- cmd/sesctl/cmd/create.go
- cmd/sesctl/cmd/edit.go
- cmd/sesctl/cmd/ping.go
- cmd/sesctl/cmd/rm.go
- cmd/sesctl/cmd/sesctl.go
- cmd/sesctl/cmd/stat.go
- cmd/sesctl/cmd/submit.go
- cmd/sesctl/cmd/util.go
- pkg/cloudscheduler/api_server.go
- pkg/cloudscheduler/authenticate.go
- pkg/cloudscheduler/builder.go
- pkg/cloudscheduler/cloudgoalmanager.go
- pkg/cloudscheduler/cloudscheduler.go
- pkg/cloudscheduler/metrics_collector.go
- pkg/datatype/event.go
- pkg/datatype/event_test.go
- pkg/datatype/job.go
- pkg/datatype/wagglemessage.go
- pkg/datatype/wagglemessage_test.go
- pkg/interfacing/http.go
- pkg/interfacing/rmq.go
- pkg/nodescheduler/builder.go
New feature:
- cloud scheduler attempts to connect to Beehive-RabbitMQ to receive scheduling events sent from nodes. For now it only checks if active science goals are received by recipient nodes
- sesctl now requires a user token to perform any scheduling action. This can be obtained from the auth service. Please ask system administrator for details
> Cloud scheduler subscribing scheduling events from nodes

- cmd/cloudscheduler/main.go
- pkg/cloudscheduler/api_server.go
- pkg/cloudscheduler/authenticate.go
- pkg/cloudscheduler/builder.go
- the cloud scheduler is updated with the new auth/access server to fetch user information and user permission table.
- if the user is "superuser" `/jobs/list` returns all jobs, and `jobs/<<id>>/status` also returns the job even if the job owner is different
> Change auth/access server

- cmd/pluginctl/cmd/deploy.go
- pkg/pluginctl/pluginctl.go
This PR adds a --dry-run flag to inspect and experiment with changes the the Kubernetes resources generated by pluginctl.
> Added mock up of dry run flag.

- pkg/nodescheduler/resourcemanager.go
This PR addresses an issue where init containers may not get scheduled due to having too high of a default memory request.
> SAGE-1699: Added resource request / limit to init container.

- pkg/interfacing/http.go
- pkg/nodescheduler/api_server.go
- pkg/nodescheduler/builder.go
- pkg/nodescheduler/nodescheduler.go
- pkg/nodescheduler/resourcemanager.go
The node scheduler had a memory leak that caused the scheduler container out-of-memory killed by Kubernetes whenever it exceeds given memory limit.
With the go profiling tool, we found that the Kubernetes Watcher in a goroutine that manages a plugin didn't get released when we terminate the goroutine, after the plugin exits.
The PR has the release code to close the goroutine cleanly.
> Fixed the memory leak in node scheduler

- .github/workflows/cicd.yaml
This PR is a small quality of life improvement.
I realized that later versions of the `setup-go` action automatically can configure build caching. This should speed building the user tools for releases when minor changes are being iterated on.
> Upgrade go-setup action to leverage cache support

- cmd/sesctl/cmd/edit.go
- cmd/sesctl/cmd/rm.go
- cmd/sesctl/cmd/submit.go
- cmd/sesctl/cmd/util.go
- pkg/cloudscheduler/api_server.go
- pkg/cloudscheduler/cloudscheduler.go
- pkg/datatype/job.go
- Fixed a bug when user submits a job multiple times. Cloud scheduler drops science goal if it exists before creating a new science goal for new submission
- superuser now can edit / remove / re-submit others jobs. When submitting, only re-submission is possible for permission override.
> a bug fix and permission override

- cmd/pluginctl/cmd/log.go
- cmd/pluginctl/cmd/profile.go
- pkg/nodescheduler/api_server.go
- pkg/nodescheduler/resourcemanager.go
- pkg/pluginctl/pluginctl.go
- Node scheduler crashes when plugin's Kubernetes watcher receives an event without the information regarding Pod/Containers state. Now, it handles those errors and safely cleans them up
- `pluginctl profile get` added `--since -10h` to query profile information with an explicit time window
> Bug fix and pluginctl profile get --since

- cmd/pluginctl/cmd/rm.go
- cmd/runplugin/main.go
- data/jobs/a_policy_example.yaml
- data/jobs/secret_env.yaml
- pkg/nodescheduler/resourcemanager.go
- pkg/nodescheduler/resourcemanager_test.go
- pkg/pluginctl/pluginctl.go
This simple change includes the functionality that allows users to specify env values from Kubernetes Secret, with the assumption that the Secret already exists inside the node. The format is,
```yaml
plugins:
- name: myplugin
image: ...
env:
MYENV: {secret.mysecret.mykey}
```
The scheduler reads `mykey` from Kubernetes Secret named `mysecret` and loads the value of it to set the environmental variable `MYENV`. Pluginctl can do the same,
```bash
pluginctl run --name test \
--entrypoint bash \
--env MYENV={secret.mysecret.mykey} \
waggle/plugin-base:1.1.1-base -- \
-c 'printenv | grep MYENV'
```
If such Secret does not exist or the Secret does not have the key, then pluginctl will raise an exception,
```bash
Error: Secret mysecret does not have the variable a. Please check.
Secret mysecret …
```
> env supports value from Secret

- cmd/pluginctl/cmd/deploy.go
- cmd/pluginctl/cmd/run.go
- go.mod
- go.sum
- pkg/datatype/plugin.go
- pkg/logger/logger.go
- pkg/nodescheduler/nodegoalmanager.go
- pkg/nodescheduler/nodescheduler.go
- pkg/nodescheduler/resourcemanager.go
- pkg/pluginctl/pluginctl.go
- pkg/pluginctl/selector_parser.go
When there is an error in running plugins, the scheduler attempts invalid transitions on the plugin state. This transition occurs because it blindly processes Kubernetes events without monitoring the transitions. For example (See the logs below), the plugin was removed because of the error "FailedMount." However, Kubernetes keeps sending those Kubernetes Events with the same error and the scheduler changed the plugin state from "inactive" (after the plugin removal) to "failed" because of the events. Then, the plugin state stays in "failed" because there will not be further Kubernetes PodFailed Events that trigger the plugin state to "inactive." Note that the plugin state has to come to "inactive" in order for it to be scheduled by its science rules.
```bash
INFO: 2024/10/03 13:55:08 …
```
> Illegal plugin state transitions

- Dockerfile
- Makefile
- pkg/nodescheduler/resourcemanager.go
- requirements.txt
This pull request includes several changes to the `pkg/nodescheduler/resourcemanager.go` file, focusing on enabling the garbage collection process using the time-to-live (TTL) settings for completed or failed pods.
* TTL settings: Set `ttlSecondsAfterFinished` to 60 seconds to reduce the time completed or failed pods remain before being cleaned up.
* Improvements to garbage collection: Added a ticker to periodically run the `RunGabageCollector` function every minute, ensuring regular cleanup of dangling pods.
> Added a garbage collector for dangling Pods
